## global setup
baseurl: ""
url: "https://visionpixel.github.io"

title: "visionpixel"
description: "Github Page from visionpixel"

## style setup
blue: 294c94
green: 91b151

# content setup
onlyYear: "%Y"

# color theme for links
theme-color: green # indigo|yellow|pink|green|stone|

# homepage information
author: Marcel Rableski
author-image: profile.jpeg

# navigation menu
show-nav-menu: false

nav-menu:
- text: About
  permalink: about

# use false to turn off any social media links
twitter: https://twitter.com/visionpixel
facebook: false
instagram: false
github: https://github.com/visionpixel
linkedin: https://linkedin.com/in/marcel-rableski
medium: false
google-scholar: false
email: false

# google analytics
google-analytics: false

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag


