## project setup
baseurl: ""
url: "https://visionpixel.github.io"
include: [".well-known"]

## theme setup
# theme
theme-color: green

# custom
style:
  blue: 294c94
  green: 91b151


## content setup
# general
title: "visionpixel"
description: "Github Page from visionpixel"
author: Marcel Rableski
author-image: profile.jpeg

# navigation menu
show-nav-menu: true
nav-menu:
  - text: Home
    permalink: /
  - text: About
    permalink: /about
  - text: Blog
    permalink: /blog

# social menu
social-menu:
  - icon: fa-twitter
    link: https://twitter.com/visionpixel
  - icon: fa-github
    link: https://github.com/visionpixel
  - icon: fa-linkedin
    link: https://linkedin.com/in/marcel-rableski

# date
onlyYear: "%Y"

# google analytics
google-analytics: false


## jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag


