# change the followings to match your Github username and repo name
baseurl: "/tailpages" # the name of your github repo
url: "https://visionpixel.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "visionpixel"
description: "Github Page from visionpixel"

# color theme for links
theme-color: green # indigo|yellow|pink|green|stone|

# homepage information
author: Marcel Rableski
author-bio: IT Consultant and Developer  # change to false to hide
author-image: false  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: false

nav-menu:
- text: About
  permalink: about

# use false to turn off any social media links
twitter: https://twitter.com/visionpixel
facebook: false
instagram: false
github: https://github.com/visionpixel
linkedin: https://linkedin.com/marcel.rableski
medium: false
google-scholar: false
email: false

# footer information
footer-msg: false
footer-msg-link: false

# google analytics
google-analytics: false

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
